FACEBOOK_APP_ID: "701278193299457"
FACEBOOK_APP_SECRET: "62be0195eec2ad538e017031e1c8b3f4"
AWS_ACCESS_KEY_ID: "AKIAIQCSCFSYCOGXPCTQ"
AWS_ACCESS_KEY_SECRET: "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"
S3_BUCKET_NAME: "spottr_development"
